# Generated by Django 4.2.1 on 2023-05-23 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "jobName",
                    models.CharField(
                        choices=[
                            ("field_lead", "Field Lead"),
                            ("field_assists", "Field Assists"),
                            ("plant_cleaning", "Plant Cleaning After Chapel"),
                            ("house_cleaning", "House Cleaning During Field"),
                            ("water_duty", "Water Duty"),
                            ("layout_forklifts", "Layout Forklifts"),
                            ("field_dried_fruit", "Field Dried Fruit"),
                            ("early_morning_forklifting", "Early Morning Forklifting"),
                            ("tunnels", "Tunnels"),
                            ("plant_lead", "Plant Lead"),
                            ("tower", "Tower"),
                            ("stacker", "Stacker"),
                            ("speed", "Speed"),
                            ("dried_fruit", "Dried Fruit"),
                            ("auger", "Auger"),
                            ("floater", "Floater"),
                            ("bin_loader", "Bin Loader"),
                            ("take_away", "Take Away"),
                            ("backside", "Backside"),
                            ("yard", "Yard"),
                            ("clean-up_lead", "Clean-up Lead"),
                            ("pressure_washer_1", "Pressure Washer 1"),
                            ("pressure_washer_2", "Pressure Washer 2"),
                            ("pressure_washer_3", "Pressure Washer 3"),
                            ("pressure_washer_4", "Pressure Washer 4"),
                            ("pressure_washer_5", "Pressure Washer 5"),
                            ("area_1", "Area 1 Middle"),
                            ("area_2", "Area 2 Inspection / Cutters"),
                            ("area_3", "Area 3 Backside / Stacker"),
                            ("sanitizer", "Sanitizer"),
                        ],
                        max_length=31,
                    ),
                ),
                ("isForkliftJob", models.BooleanField(default=False)),
                (
                    "jobType",
                    models.CharField(
                        choices=[("f", "Field"), ("p", "Plant"), ("c", "Cleanup")],
                        max_length=1,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SummerStaff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("abigail", "Abigail"),
                            ("andrew", "Andrew"),
                            ("azariah", "Azariah"),
                            ("bethany", "Bethany"),
                            ("britta", "Britta"),
                            ("bryn", "Bryn"),
                            ("emily", "Emily"),
                            ("harley", "Harley"),
                            ("heather", "Heather"),
                            ("houston", "Houston"),
                            ("ian", "Ian"),
                            ("isaac", "Isaac"),
                            ("jeffery", "Jeffery"),
                            ("kerrianna", "Kerrianna"),
                            ("madalyn", "Madalyn"),
                            ("megan", "Megan"),
                            ("milana", "Milana"),
                            ("niks", "Niks"),
                            ("noah", "Noah"),
                            ("sebastian", "Sebastian"),
                            ("sierra", "Sierra"),
                            ("skyler", "Skyler"),
                        ],
                        max_length=31,
                    ),
                ),
            ],
        ),
    ]
