# Generated by Django 4.2.1 on 2023-05-24 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("table", "0002_weekofjobassignments_weeklyjobassignment"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SummerStaff",
        ),
        migrations.RemoveField(
            model_name="weeklyjobassignment",
            name="job",
        ),
        migrations.AddField(
            model_name="weekofjobassignments",
            name="weekData",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="weekofjobassignments",
            name="weekNum",
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name="Job",
        ),
        migrations.DeleteModel(
            name="WeeklyJobAssignment",
        ),
    ]
